// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HomeList(arg1:Record<string, any>):Promise<Record<string, any>>;

export function HotList(arg1:Record<string, any>):Promise<Record<string, any>>;

export function Search(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;
