// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HomeList(arg1) {
  return window['go']['dy']['Dy']['HomeList'](arg1);
}

export function HotList(arg1) {
  return window['go']['dy']['Dy']['HotList'](arg1);
}

export function Init() {
  return window['go']['dy']['Dy']['Init']();
}

export function Search(arg1, arg2) {
  return window['go']['dy']['Dy']['Search'](arg1, arg2);
}
