// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetData(arg1, arg2) {
  return window['go']['xhs']['Xhs']['GetData'](arg1, arg2);
}

export function IsLoginSession() {
  return window['go']['xhs']['Xhs']['IsLoginSession']();
}

export function SetLoginSession(arg1) {
  return window['go']['xhs']['Xhs']['SetLoginSession'](arg1);
}
