// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {xhs} from '../models';

export function GetData(arg1:xhs.XhsType,arg2:Record<string, any>):Promise<Record<string, any>>;

export function Init(arg1:boolean):Promise<void>;

export function IsLoginSession():Promise<string>;

export function SetLoginSession(arg1:string):Promise<void>;
